const login=document.querySelector('#login'), form=document.querySelector('#settings'), keyInput=document.querySelector('#key'), saveMessage=document.querySelector('#saveMessage');
let token='', config=null, options={channels:[],roles:[]};
const get=(obj,path)=>path.split('.').reduce((v,k)=>v?.[k],obj);
const set=(obj,path,value)=>{const parts=path.split('.');let cur=obj;for(const p of parts.slice(0,-1))cur=cur[p]??=( {} );cur[parts.at(-1)]=value;};
async function api(url,init={}){const r=await fetch(url,{...init,headers:{'content-type':'application/json','authorization':`Bearer ${token}`,...init.headers}});const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(body.error||'Verbindung fehlgeschlagen.');return body;}
function hydrate(){document.querySelectorAll('[data-path]').forEach(el=>{const value=get(config,el.dataset.path);if(el.type==='checkbox')el.checked=!!value;else if(el.multiple){const selected=new Set(Array.isArray(value)?value:[]);for(const option of el.options)option.selected=selected.has(option.value);}else if(el.dataset.lines!==undefined)el.value=Array.isArray(value)?value.join('\n'):'';else el.value=value??'';});renderList('customCommands',config.customCommands||[]);renderList('prefixes',config.prefixes?.entries||[]);}
function renderList(kind,items){const root=document.querySelector(kind==='customCommands'?'#customCommands':'#prefixes');root.replaceChildren();items.forEach((item,index)=>{const row=document.createElement('div');row.className=kind==='customCommands'?'command-row':'prefix-row';const fields=kind==='customCommands'?[['name','Befehlsname','text'],['description','Beschreibung','text'],['response','Antwort','textarea'],['enabled','Aktiv','checkbox'],['private','Private Antwort','checkbox']]:[['roleId','Discord-Rolle','role'],['prefix','Emoji und Präfix','text'],['color','Rollenfarbe','color'],['priority','Priorität','number']];for(const [key,label,type] of fields){const wrap=document.createElement('label');wrap.textContent=label;let el;if(type==='textarea'){el=document.createElement('textarea');el.rows=2;}else if(type==='role'){el=document.createElement('select');el.add(new Option('— Rolle wählen —',''));for(const role of options.roles||[])el.add(new Option(role.name,role.id));el.value=item[key]||'';}else{el=document.createElement('input');el.type=type;}if(type!=='role')el.value=item[key]??(type==='color'?'#FFD700':'');if(type==='checkbox')el.checked=item[key]!==false;el.addEventListener('input',()=>item[key]=type==='checkbox'?el.checked:(type==='number'?Number(el.value):el.value));wrap.append(el);row.append(wrap);}const remove=document.createElement('button');remove.type='button';remove.className='row-remove';remove.textContent='Entfernen';remove.onclick=()=>{items.splice(index,1);renderList(kind,items)};row.append(remove);root.append(row);});}
document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`#tab-${btn.dataset.tab}`).classList.add('active');});
document.querySelector('#loginButton').onclick=async()=>{token=keyInput.value;try{config=await api('/api/config');options=await api('/api/discord-options');document.querySelectorAll('select[data-options]').forEach(select=>{const name=select.dataset.options,current=get(config,select.dataset.path)||'';select.replaceChildren(new Option('— auswählen —',''));for(const item of options[name]||[])select.add(new Option(item.name,item.id));if(current)select.value=current;});hydrate();login.hidden=true;form.hidden=false;document.querySelector('#loginError').textContent='';const status=await api('/api/status');document.querySelector('#status').textContent=`${status.bot} · ${status.guilds} Server`;}catch(e){document.querySelector('#loginError').textContent=e.message;}};
document.querySelector('#addCommand').onclick=()=>{config.customCommands??=[];config.customCommands.push({name:'mein_befehl',description:'Mein eigener Befehl',response:'Hallo {user}!',enabled:true,private:false,roleIds:[]});renderList('customCommands',config.customCommands);};
document.querySelector('#addPrefix').onclick=()=>{config.prefixes??={enabled:true,entries:[]};config.prefixes.entries??=[];config.prefixes.entries.push({roleId:'',prefix:'✨',color:'#FFD700',priority:1});renderList('prefixes',config.prefixes.entries);};
document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('input',()=>{if(!config)return;let v=el.type==='checkbox'?el.checked:el.multiple?[...el.selectedOptions].map(o=>o.value):el.value;if(el.dataset.lines!==undefined)v=v.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(el.type==='number')v=Number(v);set(config,el.dataset.path,v);}));
form.onsubmit=async event=>{event.preventDefault();try{const result=await api('/api/config',{method:'PUT',body:JSON.stringify(config)});saveMessage.textContent=result.message;setTimeout(()=>saveMessage.textContent='',5000);}catch(e){saveMessage.textContent=e.message;}};
fetch('/api/status',{headers:{authorization:`Bearer ${token}`}}).then(r=>r.ok?r.json():null).then(s=>{if(s)document.querySelector('#status').textContent=`${s.bot} · ${s.guilds} Server`}).catch(()=>{});

